name: Use Build And Publish Workflow
on:
  push:
    branches:
      - main

jobs:
  use_hello:
    uses: ABI-Interoperability-Thesis/reusable-actions/.github/workflows/build-image.yaml@main
    with:
      who-to-greet: "World"
