name: Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACTION_TOKEN }}

      - name: Build and Publish the Docker Image
        run: |
          docker build -t ghcr.io/abi-interoperability-thesis/rabbitmq-webservice .
          docker push ghcr.io/abi-interoperability-thesis/rabbitmq-webservice:latest
