name: Use Hello Workflow
on:
  push:
    branches:
      - main

jobs:
  use_hello:
    uses: ABI-Interoperability-Thesis/reusable-actions/.github/workflows/misc/hello.yaml@main
    with:
      who-to-greet: "World"
