name: Use Hello Workflow
on:
  push:
    branches:
      - main

jobs:
  use_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Hello Workflow
        uses: https://github.com/ABI-Interoperability-Thesis/reusable-actions/blob/main/misc/hello.yaml
        with:
          who_to_greet: "World"
