name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Publish Image to Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}

      - name: Build and push Docker image as current and latest
        run: |
          docker build . --tag ghcr.io/abi-interoperability-thesis/rabbitmq-webservice:${{github.ref_name}}
          docker tag ghcr.io/abi-interoperability-thesis/rabbitmq-webservice:${{github.ref_name}} ghcr.io/abi-interoperability-thesis/rabbitmq-webservice:latest
          docker push ghcr.io/abi-interoperability-thesis/rabbitmq-webservice:${{github.ref_name}}
          docker push ghcr.io/abi-interoperability-thesis/rabbitmq-webservice:latest